### ISSUE TITLE
Stripe

### ISSUE THREAD

**Issue by DaveatCor** [bitriel/bitriel-wallet#56]
E/flutter (16158): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null))
E/flutter (16158): #0      ResultParser.parse (package:stripe_platform_interface/src/result_parser.dart:16:7)
E/flutter (16158): #1      MethodChannelStripe.confirmPayment (package:stripe_platform_interface/src/method_channel_stripe.dart:99:10)
E/flutter (16158): <asynchronous suspension>
E/flutter (16158): #2      Stripe.confirmPayment (package:flutter_stripe/src/stripe.dart:267:29)
E/flutter (16158): <asynchronous suspension>

**Comment by DaveatCor** [comment]
Issue: Could not resolve com.stripe:stripe-android:20.12.+ #1000
Solve: In 
constraints {

        implementation('com.stripe:stripe-android') {

            version {
                strictly '20.11.0'
            }
        }
    }

    constraints {

        implementation('com.stripe:financial-connections') {

            version {
                strictly '20.11.0'
            }
        }
}

<img width="763" alt="Screen Shot 2022-11-01 at 7 40 48 AM" src="https://user-images.githubusercontent.com/28787774/199134633-1697b765-49a3-4ab2-b406-14c7a583af92.png">
